name: BigQuery Statcast Sync

on:
  schedule:
    # Runs every Monday at 3 AM
    - cron: '0 3 * * 1'
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2-5

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pak"))
          pak::pkg_install(c("baseballr", "bigrquery", "tidyverse", "lubridate", "DBI"))
        shell: Rscript {0}

      - name: Run BigQuery Scraper
        env:
          GCP_AUTH_JSON: ${{ secrets.BIGQUERY_JSON }}
        run: Rscript big_scrape.R
